# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: egoncalv <egoncalv@student.42lisboa.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/21 17:55:50 by egoncalv          #+#    #+#              #
#    Updated: 2023/04/21 18:05:16 by egoncalv         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPP_FLAGS = -Wall -Werror -Wextra

NAME = megaphone

SRC = megaphone.cpp

CC =  c++

$(NAME):
	@$(CC) $(CPP_FLAGS) $(SRC) -o $(NAME)
	@echo "Built megaphone"

clean:
	@rm -rf $(NAME)


